# Generated by Django 2.1.1 on 2018-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=120)),
                ('scientific_name', models.CharField(max_length=120)),
                ('location', models.TextField()),
                ('watering_frequency', models.IntegerField()),
                ('fertilizing_frequency', models.IntegerField()),
                ('date_created', models.DateField()),
                ('description', models.TextField()),
                ('description_short', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
