# Generated by Django 2.1.1 on 2018-10-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.TrackingHistory')),
            ],
        ),
    ]
