# Generated by Django 2.1.1 on 2018-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_plantheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='lighting_frequency',
            field=models.IntegerField(default=1),
        ),
    ]
