# Generated by Django 2.1.1 on 2018-09-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_remove_plant_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description_short',
            field=models.CharField(default='anything', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
