# Generated by Django 2.1.1 on 2018-10-01 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backendapp', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='profile',
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
