# Generated by Django 2.1.1 on 2018-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_plant_lighting_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_level_ar',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], default=('متوسط', 'متوسط'), max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='color_ar',
            field=models.CharField(default=[1], max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='lighting_ar',
            field=models.CharField(choices=[('قليل', 'قليل'), ('متوسط', 'متوسط'), ('قوي', 'قوي')], default=('متوسط', 'متوسط'), max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='season_ar',
            field=models.CharField(choices=[('صيف', 'صيف'), ('خريف', 'خريف'), ('ربيع', 'ربيع'), ('شتاء', 'شتاء')], default=('خريف', 'خريف'), max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='size_ar',
            field=models.CharField(choices=[('سطح المكتب', 'سطح المكتب'), ('ارضي', 'ارضي'), ('طويل', 'طويل')], default=('ارضي', 'ارضي'), max_length=120),
        ),
    ]
