# Generated by Django 2.1.1 on 2018-09-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_plant_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_on', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Plant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Profile')),
            ],
        ),
    ]
