# Generated by Django 2.1.1 on 2018-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_auto_20181104_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AddField(
            model_name='category',
            name='category_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_1des_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_1det_ar',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_2des_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_2det_ar',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_3des_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_3det_ar',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='plant',
            name='stage_4det_ar',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(default='a', max_length=120),
        ),
        migrations.AlterField(
            model_name='plant',
            name='color_ar',
            field=models.CharField(default=[1], max_length=120),
        ),
    ]
